# Netlify configuration for redirecting to Streamlit Cloud
[build]
  base = "frontend/"
  publish = "."
  command = "echo 'Redirecting to Streamlit Cloud'"

[build.environment]
  BACKEND_API_URL = "https://naruto-image-generator.onrender.com"

# Redirect all traffic to Streamlit Cloud (update URL when you deploy)
[[redirects]]
  from = "/*"
  to = "https://your-streamlit-app.streamlit.app/:splat"
  status = 301
  force = true

# Alternative: Splash page with redirect
# [[redirects]]
#   from = "/*"
#   to = "/redirect.html"
#   status = 200 